language: php

sudo: false

php:
  - 7.0

env:
  - DB=mysql

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi

before_script:
  - cd ..
  - git clone --single-branch --branch master --depth 1 https://github.com/TYPO3/TYPO3.CMS.git typo3_core
  - mv typo3_core/* .
  - composer install
  - mkdir -p typo3conf/ext
  - rm -rf typo3conf/ext/styleguide
  - mv styleguide typo3conf/ext/styleguide

script:
  - >
    echo;
    echo "Running unit tests";
    ./bin/phpunit -c components/testing_framework/Resources/Core/Build/UnitTests.xml typo3conf/ext/styleguide/Tests/Unit/
  - >
    echo;
    echo "Running functional tests";
    export typo3DatabaseName="typo3";
    export typo3DatabaseHost="localhost";
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";
    ./bin/phpunit -c components/testing_framework/Resources/Core/Build/FunctionalTests.xml typo3conf/ext/styleguide/Tests/Functional/
  - >
    echo;
    echo "Running php lint";
    find typo3conf/ext/styleguide/ -name \*.php | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
