language: php

php:
  - 7.2
  - 7.3

sudo: true

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    recipients:
      - lolli@schwarzbu.ch
    on_success: change
    on_failure: change

before_script:
  - Build/Scripts/runTests.sh -s composerInstall -p $TRAVIS_PHP_VERSION

script:
  - >
    echo "Running composer validate"
    Build/Scripts/runTests.sh -s composerValidate -p $TRAVIS_PHP_VERSION

  - >
    echo "Running unit tests";
    Build/Scripts/runTests.sh -s unit -p $TRAVIS_PHP_VERSION

  - >
    echo "Running php lint";
    Build/Scripts/runTests.sh -s lint -p $TRAVIS_PHP_VERSION

  - >
    echo "Running functional tests with mariadb";
    Build/Scripts/runTests.sh -s functional -d mariadb -p $TRAVIS_PHP_VERSION

  - >
    if [ ${TRAVIS_PHP_VERSION} = "7.2" ]; then
      echo "Running functional tests with mssql";
      Build/Scripts/runTests.sh -s functional -d mssql -p $TRAVIS_PHP_VERSION;
    else
      echo "Running functional tests with mssql not supported with PHP 7.3 yet";
    fi

  - >
    echo "Running functional tests with postgres";
    Build/Scripts/runTests.sh -s functional -d postgres -p $TRAVIS_PHP_VERSION

  - >
    echo "Running functional tests with sqlite";
    Build/Scripts/runTests.sh -s functional -d sqlite -p $TRAVIS_PHP_VERSION

  - >
    echo "Running acceptance tests";
    Build/Scripts/runTests.sh -s acceptance -p $TRAVIS_PHP_VERSION
