name: CI

on: [push, pull_request]

jobs:

  unit:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        typo3: [^10.4]
        php: ['7.2', '7.3', '7.4']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up PHP Version ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: dependencies-composer-${{ hashFiles('composer.json') }}

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies with typo3/cms-core:${{ matrix.typo3 }}
        run: |
          composer require typo3/cms-core:${{ matrix.typo3 }} --no-progress
          git checkout composer.json

      - name: CGL
        run: composer cgl

      - name: Lint PHP
        run: composer test:php:lint

      - name: Unit Tests
        run: composer test:php:unit


  func-mysql:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        typo3: [^10.4]
        php: ['7.4']

    steps:
      - name: Start database server
        run: |
          sudo /etc/init.d/mysql start

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up PHP Version ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: dependencies-composer-${{ hashFiles('composer.json') }}

      - name: Install dependencies with typo3/cms-core:${{ matrix.typo3 }}
        run: |
          composer require typo3/cms-core:${{ matrix.typo3 }} --no-progress
          git checkout composer.json

      - name: Functional Tests MySQL
        run: composer test:php:functional
        env:
          COMPOSER_PROCESS_TIMEOUT: 1200
          typo3DatabaseHost: 127.0.0.1
          typo3DatabaseName: t3func
          typo3DatabasePassword: root
          typo3DatabaseUsername: root

  func-sqlite:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        typo3: [^10.4]
        php: ['7.4']

    steps:
      - name: Start database server
        run: |
          sudo /etc/init.d/mysql start

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up PHP Version ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: dependencies-composer-${{ hashFiles('composer.json') }}

      - name: Install dependencies with typo3/cms-core:${{ matrix.typo3 }}
        run: |
          composer require typo3/cms-core:${{ matrix.typo3 }} --no-progress
          git checkout composer.json

      - name: Functional Tests SQLite
        run: composer test:php:functional
        env:
          typo3DatabaseDriver: pdo_sqlite


  func-postgres:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        typo3: [^10.4]
        php: ['7.4']

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up PHP Version ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: dependencies-composer-${{ hashFiles('composer.json') }}

      - name: Install dependencies with typo3/cms-core:${{ matrix.typo3 }}
        run: |
          composer require typo3/cms-core:${{ matrix.typo3 }} --no-progress
          git checkout composer.json

      - name: Functional Tests Postgres
        run: composer test:php:functional
        env:
          typo3DatabaseDriver: pdo_pgsql
          typo3DatabaseHost: localhost
          typo3DatabasePort: 5432
          typo3DatabaseName: postgres
          typo3DatabasePassword: postgres
          typo3DatabaseUsername: postgres

  func-mssql:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        typo3: [^10.4]
        php: ['7.4']

    services:
      mssql2017cu9:
        image: microsoft/mssql-server-linux:2017-CU9
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: "Test1234!"
          MSSQL_PID: Developer
        ports:
          - 1433:1433

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up PHP Version ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: pecl
          extensions: sqlsrv

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: dependencies-composer-${{ hashFiles('composer.json') }}

      - name: Install dependencies with typo3/cms-core:${{ matrix.typo3 }}
        run: |
          composer require typo3/cms-core:${{ matrix.typo3 }} --no-progress
          git checkout composer.json

      - name: Functional Tests SQL Server
        run: composer test:php:functional -- --exclude-group not-mssql
        env:
          typo3DatabaseDriver: sqlsrv
          typo3DatabaseName: func
          typo3DatabasePassword: "Test1234!"
          typo3DatabaseUsername: SA
          typo3DatabasePort: 1433
          typo3DatabaseCharset: utf-8
          typo3DatabaseHost: localhost

  acceptance:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        typo3: [^10.4]
        php: ['7.4']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start MySQL
        run: sudo /etc/init.d/mysql start

      - name: Set up PHP Version ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: dependencies-composer-${{ hashFiles('composer.json') }}

      - name: Install dependencies with typo3/cms-core:${{ matrix.typo3 }}
        run: |
          composer require typo3/cms-core:${{ matrix.typo3 }} --no-progress
          git checkout composer.json

      - name: Initialize TYPO3 environment
        run: |
          cp -R Tests/Acceptance/_data/typo3conf .build/web/
          cp -R Tests/Acceptance/_data/config .build/
          mkdir .build/web/fileadmin
          .build/bin/typo3cms install:generatepackagestates

      - name: Run PHP webserver
        run: |
          export APP_IP=`ip addr show eth0 | grep -Po 'inet \K[\d.]+'`
          sed -i -e "s/GITHUB_TESTHOST/$APP_IP:8888/" Tests/Acceptance/_envs/github-actions.yml
          php -S 0.0.0.0:8888 -t .build/web/ &> php.log.txt &
          sleep 2;

      - name: Test PHP webserver and initialize TYPO3 cache
        run: |
          export APP_IP=`ip addr show eth0 | grep -Po 'inet \K[\d.]+'`
          curl "$APP_IP:8888"

      - name: Run chromedriver
        run:  nohup $CHROMEWEBDRIVER/chromedriver --url-base=/wd/hub /dev/null 2>&1 &


      - name: Codeception Acceptance Tests
        run: .build/bin/codecept run acceptance --env=github-actions -c Build/codeception.yml --html --steps -vvv


      - name: Upload Codeception output
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: codeception-results
          path: Tests/Acceptance/_output/

      - name: Upload PHP log
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: php-log
          path: php.log.txt
